- name: variables from files
  hosts: localhost
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, i am learning {{Topic}} from {{Trainer}}, Duration is {{Duration}}."
      